const mockData = [
  {
    Start: 0,
    End: 5400,
    Name: "Workout",
    IsFake: false,
    TestInterval: false,
    StartTargetPowerPercent: 50,
  },
  {
    Start: 0,
    End: 600,
    Name: "Fake",
    IsFake: true,
    TestInterval: false,
    StartTargetPowerPercent: 50,
  },
  {
    Start: 600,
    End: 1500,
    Name: "Endurance 1",
    IsFake: false,
    TestInterval: false,
    StartTargetPowerPercent: 70,
  },
  {
    Start: 1500,
    End: 1560,
    Name: "Endurance 2",
    IsFake: false,
    TestInterval: false,
    StartTargetPowerPercent: 70,
  },
  {
    Start: 1560,
    End: 2400,
    Name: "Endurance 3",
    IsFake: false,
    TestInterval: false,
    StartTargetPowerPercent: 65,
  },
  {
    Start: 2400,
    End: 2460,
    Name: "Endurance 4",
    IsFake: false,
    TestInterval: false,
    StartTargetPowerPercent: 65,
  },
  {
    Start: 2460,
    End: 3300,
    Name: "Endurance 5",
    IsFake: false,
    TestInterval: false,
    StartTargetPowerPercent: 75,
  },
  {
    Start: 3300,
    End: 3360,
    Name: "Endurance 6",
    IsFake: false,
    TestInterval: false,
    StartTargetPowerPercent: 75,
  },
  {
    Start: 3360,
    End: 4200,
    Name: "Endurance 7",
    IsFake: false,
    TestInterval: false,
    StartTargetPowerPercent: 70,
  },
  {
    Start: 4200,
    End: 4260,
    Name: "Endurance 8",
    IsFake: false,
    TestInterval: false,
    StartTargetPowerPercent: 70,
  },
  {
    Start: 4260,
    End: 5100,
    Name: "Endurance 9",
    IsFake: false,
    TestInterval: false,
    StartTargetPowerPercent: 75,
  },
  {
    Start: 5100,
    End: 5400,
    Name: "Fake",
    IsFake: true,
    TestInterval: false,
    StartTargetPowerPercent: 75,
  },
];

module.exports = mockData;
